In [1]:
import torch
import numpy as np

*Change data from NumPy -> PyTorch :  torch.from_numpy(ndarray)
*Data from PyTorch tensor -> Numpy : torch.Tensor.numpy()

In [2]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype
#We can see that since the default numpy datatype is float64, so is the tensor's that is copied from the numpy array


dtype('float64')

In [4]:
#What will changing the value of the array do to the tensor?
array = array + 1
array, tensor
#it does not change the tensor!


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
# Change the tensor, what happens to np tensor?
tensor = tensor + 1
tensor, np_tensor
#we can see that they don't share memory in either way

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))