In [1]:
import torch
import numpy as np

In short, how a neural network learns:

Start with random numbers -> tensor ops -> update random numbers to try and make them better representations of the data -> again -> ...


# Reproducibility
To reduce randomness in neural networks and PyTorch comes the concept of a random seed

The random seed "flavors" the randomness

In [2]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.7931, 0.8946, 0.5078, 0.4376],
         [0.8084, 0.7456, 0.2153, 0.0725],
         [0.1556, 0.9447, 0.8282, 0.6178]]),
 tensor([[0.6752, 0.5352, 0.7019, 0.7061],
         [0.9253, 0.2890, 0.3756, 0.3506],
         [0.8652, 0.0077, 0.7550, 0.6680]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [5]:
#Set a random seed
RANDOM_SEED = 77
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.2919, 0.2857, 0.4021, 0.4645],
         [0.9503, 0.2564, 0.6645, 0.8609],
         [0.3538, 0.3347, 0.7285, 0.5794]]),
 tensor([[0.2919, 0.2857, 0.4021, 0.4645],
         [0.9503, 0.2564, 0.6645, 0.8609],
         [0.3538, 0.3347, 0.7285, 0.5794]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))