In [158]:
import torch
import pandas as pd
import numpy as np
import matplotlib as mpl
print(torch.__version__)

2.0.0


In [159]:
device = torch.device("mps")
device

device(type='mps')

# Creating Tensors

In [160]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [161]:
scalar.ndim

0

In [162]:
scalar.item()
scalar

tensor(7)

In [163]:
vector = torch.tensor([7,7])

In [164]:
vector

tensor([7, 7])

In [165]:
vector.ndim

1

In [166]:
vector.shape

torch.Size([2])

In [167]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [168]:
MATRIX.ndim

2

In [169]:
MATRIX.shape

torch.Size([2, 2])

In [170]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([1, 3, 3])
3


In [171]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### random tensors
They are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random numbers -> look at data -> repeat

In [172]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5168, 0.6604, 0.8712, 0.3973],
        [0.3181, 0.7422, 0.0154, 0.3491],
        [0.7668, 0.6368, 0.4766, 0.5314]])

In [173]:
print(random_tensor.ndim)
print(random_tensor.shape)

2
torch.Size([3, 4])


In [174]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) #color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [175]:
 #create a tensor of all zeros for a mask
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [176]:
#create tensor of ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [177]:
## Creating a range of tensors and tensors-like
# use torch.range()
torch.arange(0,10)
one_to_ten = torch.arange(1,10)

In [178]:
#creating tensors like , create tensors that are similar to preexisting ones
ten_zeros = torch.zeros_like(input = one_to_ten)

In [179]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
**datatypes can cause errors
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [180]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = torch.float32,
                              device = None,
                              requires_grad = False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [181]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [182]:
float_16_tensor * float_32_tensor
#tensors of different data types can be multiplied, but the result will take the type of the larger data type


tensor([ 9., 36., 81.])

In [183]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [184]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [185]:
##getting info from tensors
#get dtype using tensor.dtype
#get shape using tensor.shape
#get device using tensor.device

In [186]:
some_tensor = torch.rand(3,4)

In [187]:
#find out its details
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


manipulation of tensors

addition
subtraction
multiplication
division
matrix multiplication
    

In [188]:
#addition
tensor_add = torch.tensor([1,2,3])
tensor_add + 10

tensor([11, 12, 13])

In [189]:
#multiplication
tensor_mult = tensor_add.detach().clone()
tensor_mult * 10

tensor([10, 20, 30])

In [190]:
#subtraction
tensor_mult - 10

tensor([-9, -8, -7])

In [191]:
##PyTorch built-in functions
print(f"PyTorch function for Tensor Multiplication, and Addition: {torch.mul(tensor_mult, 10)}")
print(torch.add(tensor_add, 10))

PyTorch function for Tensor Multiplication, and Addition: tensor([10, 20, 30])
tensor([11, 12, 13])


In [192]:
#matrix multiplication, element wise
print(tensor_mult, "*", tensor_mult)
print(f"equals: {tensor_mult*tensor_mult}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [198]:
#dot product, since the product of 1x3 and 3x1 matrices will be 1x1

%timeit torch.matmul(tensor_mult,tensor_mult)

#runs faster than a for loop would

2.04 µs ± 32.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [199]:
#shapes for matrix mult
Tensor_A = torch.tensor([[1,2],
                        [2,3],
                        [3,4]
                        ])
Tensor_B = torch.tensor([[1,2],
                        [2,3],
                        [3,4]
                        ])
torch.mm(Tensor_A,Tensor_B)       

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [209]:
Tensor_B, Tensor_B.shape

(tensor([[1, 2],
         [2, 3],
         [3, 4]]),
 torch.Size([3, 2]))

In [201]:
Tensor_B.T, Tensor_B.T.shape

(tensor([[1, 2, 3],
         [2, 3, 4]]),
 torch.Size([2, 3]))

In [202]:
torch.mm(Tensor_A, Tensor_B.T)
# .T function converts to transpose so matrix mult works

tensor([[ 5,  8, 11],
        [ 8, 13, 18],
        [11, 18, 25]])

In [206]:
#finding summary statistics of tensors
#mean, min, max, sum, etc
x = torch.arange(0,101,10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [212]:
#max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [213]:
#average/mean
torch.mean(x), x.mean
#it looks like x is a long dtype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [214]:
x.dtype
#must be changed to appropriate dtype, the mean function can be used on tensors
# that are of dtype floating point or complex

torch.int64

In [216]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#this type conversion will fix the issue

(tensor(50.), tensor(50.))

In [217]:
#finding sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))

In [218]:
#getting the index of max value
torch.argmax(x), x.argmax()

(tensor(10), tensor(10))

In [220]:
#getting the index of min value
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

Reshaping, stacking, squeezing, and unsqueezing tensors

*Reshaping - reshapes an input tensor to a define shape
*View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor

*stacking -combines multiple tensors on top of each toehr or side by stack (vertical, horizontal)

*Squeeze - remove all '1' dimensions from a tensor

*Unsqueeze - add a '1' dimension to a target tensor

*Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [228]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [235]:
#add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [236]:
#change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x since the view of a tensor shares the same memory as the original

In [238]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [256]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked, x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([9]))

In [255]:
#squeeze and unsqueeze
x_squeezed = torch.squeeze(x)
x_squeezed, x_squeezed.shape, x.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.Size([9]))

In [267]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim = 0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [268]:
x_super_unsqueezed = torch.unsqueeze(x_unsqueezed, dim = 0)
x_super_unsqueezed, x_super_unsqueezed.shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [269]:
#torch.permute returns a view of the original tensor with dimensions swapped
x_original = torch.rand(size = (224,224,3)) #height, width, color channels (images)

#permute the original tensor to rearrange the axis or dim

x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #color channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [271]:
#indexing (selecting data from tensors)

#Indexing with PyTorch is similar to indexing with NumPy

x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [272]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [275]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [277]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [279]:
x[0][1][1], x[0][2][2]

(tensor(5), tensor(9))

In [280]:
# Using ":" to select "all" of a target dimension
x[:][0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [282]:
#Get all values of 0th and 1st dimensions, but only index 1 of second dim
x[:,:,1]

tensor([[2, 5, 8]])

In [283]:
#get all values of the 0 dimension, but only the 1 index of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [284]:
#Get index 0 of 0th and 1st dimension and all values of second dimension
x[0,0,:]

tensor([1, 2, 3])

In [285]:
#Return 2nd index of every element in dim 1 and 0
x[:,:,2]

tensor([[3, 6, 9]])